[theme]
primaryColor = "#2E86AB"
backgroundColor = "#F4F7F6"
secondaryBackgroundColor = "#EAEAEA"
textColor = "#1D2A44"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
